2024-12-16 08:32:16,426 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:32:23,565 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:33:16,973 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:34:47,286 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:35:13,575 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:36:30,292 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:36:31,936 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 08:37:04,466 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:37:30,772 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:37:32,720 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:37:44,033 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:38:04,945 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:39:11,342 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:39:31,329 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:41:16,947 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:42:03,543 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:42:39,407 - src.bot.handlers.clients.get_bonus_handler - ERROR - 'int' object has no attribute 'balance'
2024-12-16 09:57:12,460 - src.bot.handlers.clients.get_bonus_handler - ERROR - add_balance() got an unexpected keyword argument 'user'
2024-12-18 02:56:24,445 - src.database.orm.shops - ERROR - Failed to create slot: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: insert or update on table "slots" violates foreign key constraint "slots_seller_id_fkey"
DETAIL:  Key (seller_id)=(944360812) is not present in table "users".
[SQL: INSERT INTO slots (price, closed, selled, wife_id, shop_id, seller_id, created, updated) VALUES ($1::NUMERIC(25, 2), $2::BOOLEAN, $3::BOOLEAN, $4::BIGINT, $5::BIGINT, $6::BIGINT, now(), now()) RETURNING slots.id, slots.created, slots.updated]
[parameters: (Decimal('1000'), False, False, 2, 1, 944360812)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-12-18 03:20:28,988 - src.database.orm.shops - ERROR - Failed to create slot: 'coroutine' object is not subscriptable
2024-12-18 03:29:19,943 - src.database.orm.shops - ERROR - Failed to create slot: Parent instance <User at 0x7ea257d6ef30> is not bound to a Session; lazy load operation of attribute 'characters' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2024-12-18 03:32:22,381 - src.database.orm.shops - ERROR - Failed to create slot: Parent instance <User at 0x730eda1c2f60> is not bound to a Session; lazy load operation of attribute 'characters' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2024-12-18 03:32:56,454 - src.database.orm.shops - ERROR - Failed to create slot: 'User' object is not subscriptable
2024-12-18 03:33:53,058 - src.database.orm.shops - ERROR - Failed to create slot: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 03:40:17,630 - src.database.orm.shops - ERROR - Failed to create slot: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 03:42:02,803 - src.database.orm.shops - ERROR - Failed to create slot: Parent instance <User at 0x7c992e567380> is not bound to a Session; lazy load operation of attribute 'characters' cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2024-12-18 03:44:55,083 - src.database.orm.shops - ERROR - Failed to create slot: 'NoneType' object is not subscriptable
2024-12-18 03:47:27,600 - src.database.orm.shops - ERROR - Failed to create slot: 'NoneType' object is not subscriptable
2024-12-18 03:51:16,082 - src.database.orm.shops - ERROR - Failed to create slot: cannot access local variable 'session' where it is not associated with a value
2024-12-18 03:52:07,984 - src.database.orm.shops - ERROR - Failed to create slot: cannot access local variable 'session' where it is not associated with a value
2024-12-18 04:00:06,511 - src.database.orm.shops - ERROR - Failed to create slot: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 04:05:33,703 - src.database.orm.shops - ERROR - Failed to create slot: The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
2024-12-18 04:08:37,517 - src.database.orm.shops - ERROR - Failed to create slot: 'coroutine' object has no attribute 'unique'
2024-12-18 13:03:34,380 - src.database.orm.shops - ERROR - Failed to purchase slot ['this', 'buy', '1', '10']: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: ['this', 'buy', '1', '10'] ('list' object cannot be interpreted as an integer)
[SQL: SELECT slots.id, slots.price, slots.closed, slots.selled, slots.wife_id, slots.shop_id, slots.seller_id, slots.created, slots.updated, users_1.id AS id_1, users_1.user_id, users_1.username, users_1.status, users_1.vip_to, users_1.balance, users_1.profile_imgs, users_1.created AS created_1, users_1.updated AS updated_1, wifes_1.id AS id_2, wifes_1.name, wifes_1.description, wifes_1.rare, wifes_1.wife_imgs, wifes_1.from_, wifes_1.sex, wifes_1.created AS created_2, wifes_1.updated AS updated_2 
FROM slots LEFT OUTER JOIN users AS users_1 ON users_1.user_id = slots.seller_id LEFT OUTER JOIN wifes AS wifes_1 ON wifes_1.id = slots.wife_id 
WHERE slots.id = $1::BIGINT]
[parameters: (['this', 'buy', '1', '10'],)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-12-18 13:05:22,930 - src.database.orm.shops - ERROR - Failed to purchase slot ['this', 'buy', '2', '3']: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: ['this', 'buy', '2', '3'] ('list' object cannot be interpreted as an integer)
[SQL: SELECT slots.id, slots.price, slots.closed, slots.selled, slots.wife_id, slots.shop_id, slots.seller_id, slots.created, slots.updated, users_1.id AS id_1, users_1.user_id, users_1.username, users_1.status, users_1.vip_to, users_1.balance, users_1.profile_imgs, users_1.created AS created_1, users_1.updated AS updated_1, wifes_1.id AS id_2, wifes_1.name, wifes_1.description, wifes_1.rare, wifes_1.wife_imgs, wifes_1.from_, wifes_1.sex, wifes_1.created AS created_2, wifes_1.updated AS updated_2 
FROM slots LEFT OUTER JOIN users AS users_1 ON users_1.user_id = slots.seller_id LEFT OUTER JOIN wifes AS wifes_1 ON wifes_1.id = slots.wife_id 
WHERE slots.id = $1::BIGINT]
[parameters: (['this', 'buy', '2', '3'],)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-12-18 13:06:16,513 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 13:07:30,740 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 13:07:42,963 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 13:47:26,333 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 13:50:42,634 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 13:57:30,184 - src.database.orm.shops - ERROR - Failed to purchase slot 10: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 13:58:50,503 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:01:45,543 - src.database.orm.shops - ERROR - Failed to purchase slot 3: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:08:22,141 - src.database.orm.shops - ERROR - Failed to purchase slot 3: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:09:16,853 - src.database.orm.shops - ERROR - Failed to purchase slot 3: ORM mapped entity or attribute "Slot.seller" does not link from relationship "Slot.wife".
2024-12-18 14:11:02,786 - src.database.orm.shops - ERROR - Failed to purchase slot 3: ORM mapped entity or attribute "Slot.seller" does not link from relationship "Slot.wife".
2024-12-18 14:11:47,275 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:16:11,349 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:23:40,648 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:27:28,104 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:32:52,445 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 14:42:49,860 - src.database.orm.shops - ERROR - Failed to purchase slot 4: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
2024-12-18 16:00:54,943 - src.database.orm.shops - ERROR - Failed to cancel slot 3: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: bigint = character varying
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT slots.id, slots.price, slots.closed, slots.selled, slots.wife_id, slots.shop_id, slots.seller_id, slots.created, slots.updated, wifes_1.id AS id_1, wifes_1.name, wifes_1.description, wifes_1.rare, wifes_1.wife_imgs, wifes_1.from_, wifes_1.sex, wifes_1.created AS created_1, wifes_1.updated AS updated_1, users_1.id AS id_2, users_1.user_id, users_1.username, users_1.status, users_1.vip_to, users_1.balance, users_1.profile_imgs, users_1.created AS created_2, users_1.updated AS updated_2, wifes_2.id AS id_3, wifes_2.name AS name_1, wifes_2.description AS description_1, wifes_2.rare AS rare_1, wifes_2.wife_imgs AS wife_imgs_1, wifes_2.from_ AS from__1, wifes_2.sex AS sex_1, wifes_2.created AS created_3, wifes_2.updated AS updated_3 
FROM slots LEFT OUTER JOIN users AS users_1 ON users_1.user_id = slots.seller_id LEFT OUTER JOIN (user_wife_association AS user_wife_association_1 JOIN wifes AS wifes_1 ON wifes_1.id = user_wife_association_1.wife_id) ON users_1.id = user_wife_association_1.user_id LEFT OUTER JOIN wifes AS wifes_2 ON wifes_2.id = slots.wife_id 
WHERE slots.id = $1::VARCHAR]
[parameters: ('3',)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-18 16:03:43,929 - src.database.orm.shops - ERROR - Failed to cancel slot 10: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: bigint = character varying
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT slots.id, slots.price, slots.closed, slots.selled, slots.wife_id, slots.shop_id, slots.seller_id, slots.created, slots.updated, wifes_1.id AS id_1, wifes_1.name, wifes_1.description, wifes_1.rare, wifes_1.wife_imgs, wifes_1.from_, wifes_1.sex, wifes_1.created AS created_1, wifes_1.updated AS updated_1, users_1.id AS id_2, users_1.user_id, users_1.username, users_1.status, users_1.vip_to, users_1.balance, users_1.profile_imgs, users_1.created AS created_2, users_1.updated AS updated_2, wifes_2.id AS id_3, wifes_2.name AS name_1, wifes_2.description AS description_1, wifes_2.rare AS rare_1, wifes_2.wife_imgs AS wife_imgs_1, wifes_2.from_ AS from__1, wifes_2.sex AS sex_1, wifes_2.created AS created_3, wifes_2.updated AS updated_3 
FROM slots LEFT OUTER JOIN users AS users_1 ON users_1.user_id = slots.seller_id LEFT OUTER JOIN (user_wife_association AS user_wife_association_1 JOIN wifes AS wifes_1 ON wifes_1.id = user_wife_association_1.wife_id) ON users_1.id = user_wife_association_1.user_id LEFT OUTER JOIN wifes AS wifes_2 ON wifes_2.id = slots.wife_id 
WHERE slots.id = $1::VARCHAR]
[parameters: ('10',)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-18 16:04:57,729 - src.database.orm.shops - ERROR - Failed to cancel slot 3: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: bigint = character varying
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT slots.id, slots.price, slots.closed, slots.selled, slots.wife_id, slots.shop_id, slots.seller_id, slots.created, slots.updated, wifes_1.id AS id_1, wifes_1.name, wifes_1.description, wifes_1.rare, wifes_1.wife_imgs, wifes_1.from_, wifes_1.sex, wifes_1.created AS created_1, wifes_1.updated AS updated_1, users_1.id AS id_2, users_1.user_id, users_1.username, users_1.status, users_1.vip_to, users_1.balance, users_1.profile_imgs, users_1.created AS created_2, users_1.updated AS updated_2, wifes_2.id AS id_3, wifes_2.name AS name_1, wifes_2.description AS description_1, wifes_2.rare AS rare_1, wifes_2.wife_imgs AS wife_imgs_1, wifes_2.from_ AS from__1, wifes_2.sex AS sex_1, wifes_2.created AS created_3, wifes_2.updated AS updated_3 
FROM slots LEFT OUTER JOIN users AS users_1 ON users_1.user_id = slots.seller_id LEFT OUTER JOIN (user_wife_association AS user_wife_association_1 JOIN wifes AS wifes_1 ON wifes_1.id = user_wife_association_1.wife_id) ON users_1.id = user_wife_association_1.user_id LEFT OUTER JOIN wifes AS wifes_2 ON wifes_2.id = slots.wife_id 
WHERE slots.id = $1::VARCHAR]
[parameters: ('3',)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-18 16:07:48,105 - src.database.orm.shops - ERROR - Failed to cancel slot 3: The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
2024-12-21 14:38:45,412 - src.database.orm.shops - ERROR - Failed to create slot: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: insert or update on table "slots" violates foreign key constraint "slots_shop_id_fkey"
DETAIL:  Key (shop_id)=(2) is not present in table "shop".
[SQL: INSERT INTO slots (price, closed, selled, wife_id, shop_id, seller_id, created, updated) VALUES ($1::NUMERIC(25, 2), $2::BOOLEAN, $3::BOOLEAN, $4::BIGINT, $5::BIGINT, $6::BIGINT, now(), now()) RETURNING slots.id, slots.created, slots.updated]
[parameters: (Decimal('100'), False, False, 1, 2, 944360812)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
